### ISSUE TITLE
S3 URL fails with `failed to get directory specified by the source ...: relative paths require a module with a pwd`

### ISSUE THREAD

**Issue by Subhajit97** [hashicorp/go-getter#440] opened 2023-06-01 15:14 UTC
I am trying to download files from an S3 URL, but I'm getting the below error.
```
failed to get directory specified by the source <bucket>.s3-<region>.amazonaws.com/ghost/: relative paths require a module with a pwd
```

Note: I haven't provided any forced getter (i.e. `s3::`) before the source URL.

The order in the package to detect the source type seems incorrect since the Detect method checks for `FileGetter` before the actual detect method used for S3 URLs. Hence, it can't find any `pwd` value in the source.

Workaround: Mentioning forced getter (i.e. `s3::`) solves the issue.

**Comment by crw** [comment] 2023-06-01 20:00
Duplicate of #441. 

(Note that #441 seems to have slightly more detail, so closing this in favor of that.)

**Closed by crw** 2023-06-01 20:00 UTC
